services:
  redis-init:
    image: alpine:latest
    volumes:
      - ./redis.db:/mnt/redis-volume
    command: |
      sh -c '
        if ! test -f /mnt/redis-volume/redis.img; then
          apk add --no-cache e2fsprogs
          dd if=/dev/zero of=/mnt/redis-volume/redis.img bs=1M count=100
          mkfs.ext4 /mnt/redis-volume/redis.img
          mkdir -p /mnt/redis-data
          mount -o loop /mnt/redis-volume/redis.img /mnt/redis-data
          chown 999:999 /mnt/redis-data
          umount /mnt/redis-data
        fi
      '
    privileged: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ADMIN_TOKEN=${KICK_ADMIN_TOKEN}
      - CLIENT_ID=${KICK_CLIENT_ID}
      - CLIENT_SECRET=${KICK_CLIENT_SECRET}
      - LOG_LEVEL=trace
      - REDIS_URL=redis://redis:6379
      - USERS_FILE=/etc/secrets/users.txt
    volumes:
      - ${USERS_FILE:-/dev/null}:/etc/secrets/users.txt
    ports:
      - "10000:10000"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ./redis.db:/mnt/redis-volume
    command: |
      sh -c '
        mkdir -p /mnt/redis-data
        mount -o loop /mnt/redis-volume/redis.img /mnt/redis-data
        redis-server --appendonly yes --dir /mnt/redis-data
      '
    privileged: true
    depends_on:
      redis-init:
        condition: service_completed_successfully

  redis-insights:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    restart: unless-stopped
    depends_on:
      - redis
